---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taosbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taosbot
      version: v1
  template:
    metadata:
      labels:
        app: taosbot
        version: v1
    spec:
      containers:
        - image: amcchesneytaos/taosbot:latest
          imagePullPolicy: Always
          name: taosbot
          env:
            - name: SLACK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-api
                  key: apikey
