name: Build Sphinx Docs

on:
  push:
    branches:
      - feat/docs

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: Setup Git
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout ${GITHUB_HEAD_REF}

          git config --global user.email "DevOpsNow@taos.com"
          git config --global user.name "Sphinx Docs Builder"

      - name: Install Requirements
        run: |
          pip install -r dev.requirements.txt

      - name: Clean and Regenerate Docs
        run: rm -rf docs/* && python -m sphinx .docs docs && git add -f docs

      - name: Push Update
        run: |
          git commit -m "Compile Sphinx Documentation"
          git push origin feat/docs
