name: Build Sphinx Docs

on:
  push:
    branches:
      - feat/docs

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: Install Requirements
        run: |
          pip install -r dev.requirements.txt

      - name: Clean and Regenerate Docs
        run: rm -rf docs/* && python -m sphinx .docs docs && git add -f docs

      - name: Commit files
        run: |
          git config --global user.email "DevOpsNow@taos.com"
          git config --global user.name "Sphinx Docs Builder"

          git commit -m "Compile Sphinx Documentation"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: feat/docs
