name: CI

on:
  push:
    branches:
      - feat/cloud-email

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Requirements
        run: mv serverless.requirements.txt requirements.txt

      - name: Set Requirements
        run: pip install -r requirements.txt

      - name: Log into gcp
        run: |
          echo "${GCP_KEY}" > /tmp/gcpkey.json
          gcloud auth activate-service-account --key-file=/tmp/gcpkey.json
          gcloud config set project ${GCP_PROJECT}
          gcloud functions deploy taos-cli-contact  \
            --runtime python37 --trigger-http --entry-point cloud_function \
            --set-env-vars=SEND_GRID_API_KEY=${SEND_GRID_API_KEY},SUPPORT_EMAIL=${SUPPORT_EMAIL},CONTACT_EMAIL=${CONTACT_EMAIL}
        env:
          GCP_KEY: ${{ secrets.GCP_KEY }}
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          SEND_GRID_API_KEY: ${{ secrets.SEND_GRID_API_KEY }}
          SUPPORT_EMAIL: ${{ secrets.SUPPORT_EMAIL }}
          CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
